Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
opcao_turno:inteiro
turno:caractere


Inicio
    escreval("==== Bem Vindo! ===")
    escreval("==== Escala de Plantões ====")
    
    // ================================
    // US01 - Selecionar Turno
    // ================================
    escreval ("==== Seleção do Turno ====")
    escreval ("1 - Manhã")
    escreval ("2 - tarde")
    


Fimalgoritmo